#################### Macros #####################

PROJ = Simplex

OBJECTS = Lexer Parser
INCLUDE = src

TARGETNAME = Simplex
TARGET_OBJECTS = Main

TESTERNAME = Test
TESTER_OBJECTS = LexerTests ParserTests TesterMain

# CC macros
COMMON_CFLAGS = -static-libgcc
CFLAGS = -O0 -g
CDEFINES =

# CPP macros (additional to C macros)
COMMON_CPPFLAGS = -static-libstdc++
CPPFLAGS = 
CPPDEFINES =

# Universal macros
LIBS = 
CUSTOM_INCLUDES = 
SOURCE = src
TARGET = .

include cpp_exec.mk