#################### Macros #####################

PROJ = Parser

TARGETNAME = Parser
OBJECTS = Lexer Parser
INCLUDE = src

# CC macros
COMMON_CFLAGS = -static-libgcc
CFLAGS = -O0 -g
CDEFINES =

# CPP macros (additional to C macros)
COMMON_CPPFLAGS = -static-libstdc++
CPPFLAGS = 
CPPDEFINES =

# Universal macros
LIBS = 
CUSTOM_INCLUDES = 
SOURCE = src
TARGET = .

include cpp_exec.mk